### PR TITLE
Resolve all native dependencies into the root project

### PR DESCRIPTION
**Pull request by ThadHouse**
Helps ensure things are never duplicate resolved in multi project builds.

I'm asking a few question in the gradle slack on if this is 100% reliable, but I was doing it in the old native utils and never had an issue.

### CODE REVIEW

**Comment by ThadHouse** [comment]
Closes #45

**Comment by JacisNonsense** [comment]
I think I'll hold off on this until we get some more data. I can't make a good judgement on whether this is going to be stable or not

**Comment by ThadHouse** [comment]
I agree. It's been stable in my testing and was stable in the old native utils, but I would be nice to know how safe.

Maybe I'll hide it behind a flag. Allwpilib needs it badly, as otherwise configuration takes almost 10 minutes the first time. But could leave the default for teams, and just set the flag in allwpilib itself.

**Comment by ThadHouse** [comment]
Ok, I updated it to keep all the dependencies in their projects, but use `project.rootProject.zipTree`. This causes all files to extract to the root project, but looking through the source code of ZipTree this is much safer to perform. 

https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/file/archive/ZipFileTree.java

**Comment by ThadHouse** [comment]
https://github.com/gradle/gradle/pull/8364/files

Oh, we should be using an artifact transform for this. I'll take a look into that.

**Comment by ThadHouse** [comment]
Though some testing, it seems like the artifact transform is safe, because the transform is performed on the config, not on the dependency itself. So it might break things like mixed mode android project, but I don't  think we need to support that in the same project. I think this is ok to merge now, as I haven't been able to break anything yet.

**Pull request merged**
